"""Phase 4 — profile every raw dataset (schema, null rates, duplicates, samples).

Scans data/raw/**/*.{csv,xlsx}, reads each as strings (no dtype inference — that's
Phase 5's job), and writes a machine profile to results/profiles/<key>.json plus a
human-readable results/profiles/SUMMARY.md. Read-only on raw (CLAUDE.md §2.6).

A blank/whitespace-only cell counts as missing. Run:
    .venv/Scripts/python.exe src/validate/profile.py
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

try:
    import pandas as pd
except ModuleNotFoundError:
    sys.exit("pandas not installed — run: .venv/Scripts/python.exe -m pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "results" / "profiles"

SKIP_NAMES = {"DROP_HERE.md", ".gitkeep"}


DELIMITERS = [",", "|", "\t", ";"]


def load(path: Path) -> tuple[pd.DataFrame, str, str]:
    """Return (df_as_strings, encoding, delimiter). Encoding is tried utf-8 -> cp1252 ->
    latin-1 (latin-1 always decodes); the delimiter is chosen by counting candidates in
    the header line — csv.Sniffer mis-detected the pipe-delimited Oregon export."""
    if path.suffix.lower() in (".xlsx", ".xls"):
        return pd.read_excel(path, dtype=str, engine="openpyxl"), "xlsx", "xlsx"
    raw = path.read_bytes()
    text = enc = None
    for e in ("utf-8", "cp1252", "latin-1"):
        try:
            text, enc = raw.decode(e), e
            break
        except UnicodeDecodeError:
            continue
    header = text.splitlines()[0] if text else ""
    sep = max(DELIMITERS, key=header.count)
    if header.count(sep) == 0:
        sep = ","
    df = pd.read_csv(io.StringIO(text), sep=sep, dtype=str, keep_default_na=False, na_values=[])
    return df, enc, sep


def profile_one(path: Path) -> dict:
    df, encoding, delimiter = load(path)
    # normalize: strip; blanks -> NA for missingness stats
    norm = df.apply(lambda c: c.str.strip() if c.dtype == object else c)
    blank = norm.replace("", pd.NA)

    n_rows, n_cols = df.shape
    cols = []
    for c in df.columns:
        s = blank[c]
        non_null = int(s.notna().sum())
        examples = [v for v in s.dropna().unique()[:3].tolist()]
        cols.append({
            "name": str(c),
            "non_null": non_null,
            "blank_pct": round(100 * (n_rows - non_null) / n_rows, 1) if n_rows else None,
            "n_unique": int(s.nunique(dropna=True)),
            "examples": [str(x)[:60] for x in examples],
        })
    dup_rows = int(df.duplicated().sum())
    return {
        "file": path.relative_to(ROOT).as_posix(),
        "encoding": encoding,
        "delimiter": delimiter,
        "rows": int(n_rows),
        "cols": int(n_cols),
        "duplicate_full_rows": dup_rows,
        "columns": cols,
    }


def main() -> int:
    files = sorted(
        p for p in RAW.rglob("*")
        if p.is_file() and p.suffix.lower() in (".csv", ".xlsx", ".xls") and p.name not in SKIP_NAMES
    )
    if not files:
        print("No raw data files found under data/raw/.")
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    summary_lines = ["# Raw dataset profiles\n", "_Generated by src/validate/profile.py — read-only on raw._\n"]
    for path in files:
        key = f"{path.parent.name}__{path.stem}"
        try:
            prof = profile_one(path)
        except Exception as e:  # noqa: BLE001
            print(f"!! FAILED {path.name}: {e}")
            summary_lines.append(f"\n## {key}\n- **FAILED to profile:** {e}\n")
            continue
        (OUT / f"{key}.json").write_text(json.dumps(prof, indent=2), encoding="utf-8")
        print(f">> {key}: {prof['rows']} rows x {prof['cols']} cols, dup_rows={prof['duplicate_full_rows']}")

        summary_lines.append(f"\n## {key}\n")
        summary_lines.append(f"- file: `{prof['file']}`\n")
        summary_lines.append(f"- shape: **{prof['rows']} rows x {prof['cols']} cols**, "
                             f"encoding: {prof['encoding']}, delimiter: `{prof['delimiter']}`, "
                             f"full-duplicate rows: {prof['duplicate_full_rows']}\n")
        high_blank = [c for c in prof["columns"] if (c["blank_pct"] or 0) >= 90]
        if high_blank:
            summary_lines.append(f"- {len(high_blank)} columns are >=90% blank\n")
        summary_lines.append("- columns (name | blank% | unique):\n")
        for c in prof["columns"]:
            summary_lines.append(f"  - `{c['name']}` | {c['blank_pct']}% | {c['n_unique']}\n")

    (OUT / "SUMMARY.md").write_text("".join(summary_lines), encoding="utf-8")
    print(f">> wrote {len(files)} profile(s) to {OUT.relative_to(ROOT).as_posix()}/ (+ SUMMARY.md)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
